geoscience-unifr example:
### Finding smallest person in class

In [1]:
# using logic operators to find smaller value
3 < 4

True

In [2]:
if 3 < 4:
    print("smaller value is 3")

smaller value is 3


In [3]:
# with variables
a = 3
b = 4
if a < b:
    print("smaller value is", a)

smaller value is 3


In [4]:
# using also a variable to store the smalles value 
# here using the value of variable b to start with

a = 3
b = 4
smallest_value = b
print("smallest value at start is:", smallest_value)

if a < b:
    smallest_value = a

print("smallest value at end is:", smallest_value)



smallest value at start is: 4
smallest value at end is: 3


In [5]:
# creating random "heights" in a matrix (2D) with 6 rows and 5 columns
import numpy as np

# 30 random values with mean=170, sd=10, n=30:
r30 = np.random.normal(170,10,30)

# assigning those 30 values to a
# 6 x 5 matrix (.reshape(rows,columns)) 
# and transform the values to integer type (.astype(int))
cr = np.array(r30).reshape((6,5)).astype(int)

In [6]:
cr

array([[157, 184, 156, 161, 178],
       [183, 152, 186, 180, 174],
       [158, 149, 163, 163, 168],
       [170, 170, 184, 166, 160],
       [159, 178, 166, 160, 181],
       [147, 178, 159, 175, 173]])

In [7]:
# number of rows and columns (2 values as tuple) stored in the matrix parameter called "shape"
cr.shape

(6, 5)

In [8]:
# save as two variables (separated with ",")
rows, cols = cr.shape

In [9]:
# going through each entry, row by row, and column by column
min_value = cr[0,0]
for h in range(cols):
    # example first row (cr[0,h]) << 0th row 
    print(cr[0,h])


157
184
156
161
178


In [10]:
# going through each entry, row by row, and column by column
min_value = cr[0,0]
for c in range(cols):
    # example first row (cr[0,c]) << 0th row 
    # whenever cr[0,h] is smaller than min_value, overwrite the value of min_value with the new value
    if cr[0,c] < min_value:
        min_value = cr[0,c]
print(min_value)


156


In [11]:
# do the same but iterate also through all the rows (> cr[r,c]
min_value = cr[0,0]
for r in range(rows):
    for c in range(cols):
        # print(cr[r,c])
        if cr[r,c] < min_value:
            min_value = cr[r,c]
print(min_value)

147


In [12]:
# getting the positions (indices: row and column) instead of the actual value:
min_value = cr[0,0]
min_value_indices = [0,0] # < list with two entries for inices of row and column
for r in range(rows):
    for c in range(cols):
        # print(cr[r,c])
        if cr[r,c] < min_value:
            min_value = cr[r,c]
            min_value_indices = [r,c] # only row and column indices
print(min_value)
print(min_value_indices)

147
[5, 0]


In [13]:
# check if the indices do actually give the minimum number:
cr[min_value_indices[0], min_value_indices[1]]

np.int64(147)

In [14]:
# Attention: the variable "min_value_indices" is a list
# If directly put in as index into "cr" it will yield rows 1 and 4:
# cr[[1,4]]
cr[min_value_indices]

array([[147, 178, 159, 175, 173],
       [157, 184, 156, 161, 178]])

In [15]:
cr[[1,4],]

array([[183, 152, 186, 180, 174],
       [159, 178, 166, 160, 181]])

### Indices over values
Why getting the indices can be advantageous over finding just the smalles value?

In [16]:
# another table (matrix) that stores another variable, for example the person's ID (here A1:A30)
IDs = range(30)
IDs = ["A"+ str(i+1) for i in IDs]
ids = np.array(IDs).reshape(6,5)
ids

array([['A1', 'A2', 'A3', 'A4', 'A5'],
       ['A6', 'A7', 'A8', 'A9', 'A10'],
       ['A11', 'A12', 'A13', 'A14', 'A15'],
       ['A16', 'A17', 'A18', 'A19', 'A20'],
       ['A21', 'A22', 'A23', 'A24', 'A25'],
       ['A26', 'A27', 'A28', 'A29', 'A30']], dtype='<U3')

In [17]:
# which person ID corresponds to the smallest identified person?

# Using the indices to find the smalles value:
cr[min_value_indices[0], min_value_indices[1]]


np.int64(147)

In [18]:
# Using the same indices but now in the table of person IDs
ids[min_value_indices[0], min_value_indices[1]]

np.str_('A26')